---
releases:
  - name: syslog
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/syslog-0.1.3.tgz
    sha1: d7048c6205929365b7de60c03b6dd16531c29d5d

addons:
  - name: syslog_forwarder
    jobs:
      - name: syslog_forwarder
        release: syslog
        properties:
          syslog:
            address: (( concat "logsearch-ingestor." $SYSTEM_DNS_ZONE_NAME ))
            port: 6514
            transport: 'tcp'
            tls_enabled: true
            permitted_peer: (( concat "*." $SYSTEM_DNS_ZONE_NAME ))
            custom_rule: |
              $MaxMessageSize 64k
              if ($programname startswith "vcap.") then stop
            use_tcp_for_file_forwarding_local_transport: true
