---
releases:
  - name: datadog-agent
    version: 0.1.5
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-agent-0.1.5.tgz
    sha1: 573bed2ab7960eb97dafff4b7c6111e7ad72b39c

addons:
  - name: datadog-agent
    jobs:
      - name: datadog-agent
        release: datadog-agent
        properties:
          enabled: true
          api_key: (( grab $DATADOG_API_KEY ))
          application_key: (( grab $DATADOG_APP_KEY ))
          use_dogstatsd: false
          include_bosh_tags: true
          tags:
            aws_account: (( grab $AWS_ACCOUNT ))
            deploy_env: (( grab terraform_outputs.environment ))
          integrations:
            process:
              init_config:

              instances:
                - name: btrfs
                  search_string: ["btrfs"]
            dns_check:
              init_config:
              instances:
                - name: Canary
                  hostname: (( concat "__canary." $SYSTEM_DNS_ZONE_NAME ))
