---
releases:
  - name: datadog-agent
    version: 0.1.4
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-agent-0.1.4.tgz
    sha1: a1902a885ef465617eae4f1de184ecaed0d1feb8

meta:
  datadog:
    enabled: (( grab $ENABLE_DATADOG ))
    api_key: (( grab $DATADOG_API_KEY || "undefined" ))
    application_key: (( grab $DATADOG_APP_KEY || "undefined" ))
    use_dogstatsd: false
    include_bosh_tags: true
    tags:
      aws_account: (( grab $AWS_ACCOUNT ))
      deploy_env: (( grab terraform_outputs.environment ))
    integrations:
      process:
        init_config:

        instances:
          - name: btrfs
            search_string: ["btrfs"]
