---
- type: remove
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/clients/bosh_cli

- type: remove
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/clients/uaa_admin

- type: remove
  path: /instance_groups/name=bosh/jobs/name=uaa/properties/uaa/scim/users
